### ISSUE TITLE
Ambiguidade na descrição da funcionalidade "solicitar bilhete"

### ISSUE THREAD

**Issue by pfreitasbarbosa** [sociedade-do-pastel/Source-Code-Inspection-PF#2]
Não está claro se o objetivo da funcionalidade "Solicitar bilhete" deve possibilitar a emissão de vários bilhetes de uma vez ou se, caso o Ator quiser emitir _n_ bilhetes, o Ator deve realizar a mesma ação _n_ vezes.

Sugestão: declarar explicitamente o comportamento desejado da funcionalidade na descrição do projeto (["1 Engenharia de Requisitos"](https://github.com/sociedade-do-pastel/Source-Code-Inspection-PF/wiki/1-Documenta%C3%A7%C3%A3o-de-requisitos#1-engenharia-de-requisitos)).

**Comment by uniefelsousa** [comment]
Foi refeito o parágrafo com a seguinte frase:
As estações de trem frequentemente fornecem máquinas de vender bilhetes que imprimem
um bilhete por vez, quando um cliente insere a quantia correta para pagar essa passagem. Caso
seja necessário a compra de mais bilhetes, o cliente terá que realizar a operação mais vezes.

**Comment by pfreitasbarbosa** [comment]
Corrigido conforme comentário acima.
