### ISSUE TITLE
Inexistência de ação para debitar o valor do bilhete no saldo atual

### ISSUE THREAD

**Issue by pfreitasbarbosa** [sociedade-do-pastel/Source-Code-Inspection-PF#3]
Não existe ação do sistema indicando o débito referente ao valor do bilhete impresso.

Sugestão: alterar o fluxo principal na documentação ("[1.3.2. CSU02 - Solicitar bilhete](https://github.com/sociedade-do-pastel/Source-Code-Inspection-PF/wiki/1-Documenta%C3%A7%C3%A3o-de-requisitos#132-csu02---solicitar-bilhete)"), adicionando o débito no fluxo de ações do sistema.

**Comment by uniefelsousa** [comment]
Foi adicionado no fluxo do caso de uso "Solicitar bilhete" a seguinte ação:
O Sistema debita o valor do bilhete no saldo atual.

**Comment by pfreitasbarbosa** [comment]
Corrigido conforme comentário acima.
